export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_TRAINING_PLANS = 'GET_TRAINING_PLANS';
export const DELETE_TRAINING_PLAN = 'DELETE_TRAINING_PLAN';
export const GET_TRAINING_PLAN_BY_ID = 'GET_TRAINING_PLAN_BY_ID';
export const ADD_NEW_TRAINING = 'ADD_NEW_TRAINING';

export const GET_EXERCISE_PLANS = 'GET_EXERCISE_PLANS';
export const DELETE_EXERCISE_PLAN = 'DELETE_EXERCISE_PLAN';
